[Logging]
  Disable = false
  Level = "DEBUG"
  File = ""

[UpstreamProxy]
  Type = "none"

[Debug]
  DisableDecoyTraffic = true
  CaseSensitiveUserIdentifiers = false
  PollingInterval = 1

[Katzenmint]
    ChainID = "test-chain-QvpdAC"
    PrimaryAddress = "tcp://127.0.0.1:26657"
    WitnessesAddresses = ["tcp://127.0.0.1:26657"]
    DatabaseName = "test_meson_server_pkiclient"
    DatabaseDir = "/tmp/meson_server/server_data"
    RPCAddress = "tcp://127.0.0.1:26657"

    [Katzenmint.TrustOptions]
      Period = 60000000000000
      Height = 8
      Hash = [244, 83, 245, 63, 184, 247, 216, 198, 228, 120, 159, 135, 186, 59, 221, 244, 218, 145, 174, 187, 162, 80, 44, 198, 89, 33, 0, 189, 236, 230, 35, 199]