{
 "title": "Meson Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Cryptworker packet error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(katzenpost_crypto_worker_dropped_packets_total{}[$__interval])",
     "legendFormat": "drop({{instance}})"
    },
    {
     "expr": "rate(katzenpost_crypto_worker_replayed_packets_total{}[$__interval])",
     "legendFormat": "replayed({{instance}})"
    }
   ]
  },
  {
   "title": "Decoy packet error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(katzenpost_decoy_dropped_packets_total{}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "kaetzchen request error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(katzenpost_kaetzchen_dropped_requests_total{}[$__interval])",
     "legendFormat": "drop request({{instance}})"
    },
    {
     "expr": "rate(katzenpost_kaetzchen_failed_requests_total{}[$__interval])",
     "legendFormat": "failed request({{instance}})"
    }
   ]
  },
  {
   "title": "Katzenpost In/Out packet error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(katzenpost_incoming_conn_dropped_packets_total{}[$__interval])",
     "legendFormat": "incoming drop({{instance}})"
    },
    {
     "expr": "rate(katzenpost_outgoing_conn_dropped_packets_total{}[$__interval])",
     "legendFormat": "outgoing drop({{instance}})"
    },
    {
     "expr": "rate(katzenpost_outgoing_conn_canceled_outgoing_connections_total{}[$__interval])",
     "legendFormat": "outgoing cancel({{instance}})"
    }
   ]
  }
 ]
}