language: python
install:
  sudo pip install mkdocs
script:
  - [ $TRAVIS_BRANCH == "master" ] && mkdocs build -d site
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: ./site
  on:
    branch: master
cache: pip
