language: python
install:
  sudo pip install mkdocs
script:
  - mkdocs build -d site
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: ./site
  on:
    all_branches: true
cache: pip
