site_name: Meson
nav:
    - "Home": "index.md"
    - "Overview": "overview.md"
    - "Docs": "docs.md"
    - "Contribute": "contribute.md"
    - "Contact": "contact.md"
repo_url: https://github.com/hashcloak/Meson
site_url: https://docs.mesonmix.net/
