name: All

on: ["push", "pull_request"]

jobs:

  build_and_test:
    name: "Run tests and build artifacts"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        go: ["1.19.x", "1.20.x", "1.21.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      name: "Install Golang"
      with:
        go-version: ${{ matrix.go }}
    
    - uses: actions/checkout@v3
    
    - name: "Test all"
      run: |
        make test-all

    - name: "Build all"
      run: |
        make build-all
        mkdir dist
        mv katzenmint/katzenmint dist
        mv server/meson-server dist
        mv plugin/meson-plugin dist
        mv genconfig/genconfig dist

    - if: runner.os == 'macOS'
      name: "Setup filename"
      run: echo "ZIPNAME=meson_darwin_${{ matrix.go }}" >> $GITHUB_ENV

    - if: runner.os == 'Linux'
      name: "Setup filename"
      run: echo "ZIPNAME=meson_linux_${{ matrix.go }}" >> $GITHUB_ENV

    - name: Archive all
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ZIPNAME }}
        path: dist
