name: Client

on: ["push", "pull_request"]

jobs:

  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        go: ["1.19.x", "1.20.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Lint and Test client
      run: |
        cd client
        make
